### ISSUE TITLE
Documentation for config and local git hooks 

### ISSUE THREAD

**Issue by gondek** [JScott/robot_sweatshop#13]
I had the following questions when setting up robot sweatshop:
1. Is there any way to post a local git repository's data to robot sweatshop from a post-commit git hook?
2. Does adding part of a `.robot_sweatshop` directory to a repository make sense within the intended usage/setup of robot sweatshop (like a `.travis.yml` file)? Or are the directories in the best practice `config.yaml` the way to go?

**Comment by JScott** [comment]
1. You should be able to use the same method that's in the README quick start to send arbitrary JSON in your hook. I would guess something like `curl -d '{author: $GIT_AUTHOR_NAME}' localhost:8080/payload-for/example`
2. The defaults of the current directory are for ease of use, especially with users who don't have system privileges. In production I use something that looks more like this: https://github.com/JScott/robot_sweatshop/wiki/Best-Practices#configyaml

I'm going to close the ticket since these are both in the existing docs. However, if you have any more questions then feel free to continue the discussion here. I welcome ways to improve the documentation and will be going over it again before I hit 1.0.

**Comment by JScott** [comment]
Oh, I also sit in the #robot_sweatshop channel on Freenode and have a Gitter room that the badge in the README links to. Either of those are great places to ask me questions as well :)

**Comment by gondek** [comment]
Thanks for the clarification!
